version: "3.7"

services:
  hasura:
    environment:
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key":""}'
  handler:
    environment:
      DISCORD_TOKEN: ""
      GITHUB_TOKEN: ""
  api:
    environment:
      DISCORD_TOKEN: ""
      JWT_SECRET: ""
      DISCORD_CLIENT_ID: ""
      DISCORD_CLIENT_SECRET: ""
  gateway:
    environment:
      DISCORD_TOKEN: ""
